# Generated by Django 4.1.7 on 2023-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_artist_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
