# Generated by Django 4.1.7 on 2023-03-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Bluegrass', 'Bluegrass'), ('Classical', 'Classical'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Pop', 'Pop'), ('Reggae', 'Reggae'), ('Rock', 'Rock')], max_length=50),
        ),
    ]
