# Generated by Django 4.1.7 on 2023-03-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Alt', 'alt'), ('Bluegrass', 'bluegrass'), ('Classical', 'classical'), ('Country', 'Country'), ('Electronic', 'Electronic'), ('Hip Hop', 'Hip Hop'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Pop', 'Pop'), ('Reggae', 'Reggae'), ('Rock', 'Rock')], max_length=50),
        ),
    ]
